//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudyApi.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageClient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageClient() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudyApi.Properties.Resources.MessageClient", typeof(MessageClient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome enviado não é válido!.
        /// </summary>
        public static string MC0001 {
            get {
                return ResourceManager.GetString("MC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar o nome!.
        /// </summary>
        public static string MC0002 {
            get {
                return ResourceManager.GetString("MC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email enviado não é válido!.
        /// </summary>
        public static string MC0003 {
            get {
                return ResourceManager.GetString("MC0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar um email!.
        /// </summary>
        public static string MC0004 {
            get {
                return ResourceManager.GetString("MC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone enviado não é válido!.
        /// </summary>
        public static string MC0005 {
            get {
                return ResourceManager.GetString("MC0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar uma senha!.
        /// </summary>
        public static string MC0006 {
            get {
                return ResourceManager.GetString("MC0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar a idade!.
        /// </summary>
        public static string MC0007 {
            get {
                return ResourceManager.GetString("MC0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar o CPF.
        /// </summary>
        public static string MC0008 {
            get {
                return ResourceManager.GetString("MC0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF enviado não é válido!.
        /// </summary>
        public static string MC0009 {
            get {
                return ResourceManager.GetString("MC0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar o RG.
        /// </summary>
        public static string MC0010 {
            get {
                return ResourceManager.GetString("MC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar a data de aniversário!.
        /// </summary>
        public static string MC0011 {
            get {
                return ResourceManager.GetString("MC0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar uma data de aniversário válida!.
        /// </summary>
        public static string MC0012 {
            get {
                return ResourceManager.GetString("MC0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar o endereço!.
        /// </summary>
        public static string MC0013 {
            get {
                return ResourceManager.GetString("MC0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar um CEP válido!.
        /// </summary>
        public static string MC0014 {
            get {
                return ResourceManager.GetString("MC0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar um CEP!.
        /// </summary>
        public static string MC0015 {
            get {
                return ResourceManager.GetString("MC0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar o tipo de acesso!.
        /// </summary>
        public static string MC0016 {
            get {
                return ResourceManager.GetString("MC0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar o gênero!.
        /// </summary>
        public static string MC0017 {
            get {
                return ResourceManager.GetString("MC0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessário enviar uma senha válida!.
        /// </summary>
        public static string MC0018 {
            get {
                return ResourceManager.GetString("MC0018", resourceCulture);
            }
        }
    }
}
